replicaCount: 1

image:
  repository: public.ecr.aws/aws-containers/retail-store-sample-checkout
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

redis:
  host: ""
  port: 6379

messaging:
  queueUrl: ""

resources:
  requests:
    cpu: 128m
    memory: 256Mi
  limits:
    cpu: 256m
    memory: 512Mi
