apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-orders
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-orders
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-orders
    spec:
      containers:
      - name: orders
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom"
        - name: SPRING_PROFILES_ACTIVE
          value: "mysql,rabbitmq"
        - name: SPRING_DATASOURCE_WRITER_URL
          value: "jdbc:mariadb://{{ .Values.db.host }}:5432/orders"
        - name: SPRING_DATASOURCE_READER_URL
          value: "jdbc:mariadb://{{ .Values.db.host }}:5432/orders"
        - name: SPRING_DATASOURCE_WRITER_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: SPRING_DATASOURCE_WRITER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: SPRING_DATASOURCE_READER_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: SPRING_DATASOURCE_READER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
