apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-orders
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080