apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cart
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cart
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cart
    spec:
      containers:
      - name: cart
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dynamodb"
        - name: CARTS_DYNAMODB_TABLENAME
          value: {{ .Values.dynamodb.tableName | quote }}
        - name: CARTS_DYNAMODB_CREATETABLE
          value: "false"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
