apiVersion: v1
kind: Service
metadata:
  name: carts
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-cart
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
