apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui
    spec:
      containers:
      - name: ui
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom"
        - name: ENDPOINTS_CATALOG
          value: "http://catalog"
        - name: ENDPOINTS_CARTS
          value: "http://carts"
        - name: ENDPOINTS_ORDERS
          value: "http://orders"
        - name: ENDPOINTS_CHECKOUT
          value: "http://checkout"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
