apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: devops-app-config
        - secretRef:
            name: devops-app-secret